apiVersion: v1
kind: Pod
metadata:
  name: medicus
  namespace: default
spec:
  containers:
  - name: medicus
    image: europe-central2-docker.pkg.dev/jutromedical-dev/jutro/medicus:latest
    command: ["sleep", "3600"]
    stdin: true
    tty: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["NET_RAW"]
  restartPolicy: Never
